### ISSUE TITLE
Punctuation around "however"

### ISSUE THREAD

**Issue by abbycross** [IBM/ibm-quantum-style-guide#10]
correct punctuation usage around the word "however": semicolon + however + comma
  
For example:  
`We wished to enforce fancy punctuation; however, we were thwarted.`

**Additional information**

I often see a comma before "however" with no punctuation afterward. 

For example: 

`This sentence is incorrect, however it is a common mistake.`

**Comment by frankharkins** [comment]
I can literally match `, however`, but would this have any false positives?

For example, is this sentence correct?
> This is logical, however strange it may seem.

**Comment by abbycross** [comment]
Yep, there are exceptions -- maybe this could show up as a suggestion rather than an error, with an example of right/wrong usage?
