### ISSUE TITLE
Should we warn against sentence length?

### ISSUE THREAD

**Issue by frankharkins** [IBM/ibm-quantum-style-guide#17]
We've inherited a rule (`IBMQuantum.SentenceLength`) that suggests shortening any sentences above 25 words. This could be a problem as many pages have _lots_ of >25-word sentences. This means the rule is particularly noisy, and may lead to other rules being lost / ignored. Simply shortening all the sentences isn't trivial and would require a lot of work.

Here's an example from the runtime repo (this is just part of the output):
<img height="750" alt="Screenshot 2023-03-03 at 15 35 51" src="https://user-images.githubusercontent.com/36071638/222761668-bda31c18-51b4-4171-a4c6-43ee13841bf2.png">

I see three options, but not sure which is best:

1. Leave the rule as-is and set a future goal to rewrite sentences to be below 25 words 
2. Change the rule to be less strict (for example, matching >35 words)
3. Remove the rule completely, if this is something we don't care about

**Comment by jyirinec** [comment]
Interesting question! I vote for option 3 (leave the rule out) because if IBM Quantum prefers sentences under 25 words and we enforce a rule that says 35, we might as well go with option 3.

**Comment by abbycross** [comment]
I'm also happy to remove the rule completely since it seems nearly impossible to avoid long sentences when quantum computing is involved...!

**Comment by frankharkins** [comment]
Sounds good, I'll remove it.
